import { useState } from "react"
import { Pie, Bar, Line } from "react-chartjs-2"
import {
Chart as ChartJS,
ArcElement,
CategoryScale,
LinearScale,
BarElement,
LineElement,
PointElement,
Tooltip,
Legend
} from "chart.js"

import jsPDF from "jspdf"
import html2canvas from "html2canvas"

ChartJS.register(
ArcElement,
CategoryScale,
LinearScale,
BarElement,
LineElement,
PointElement,
Tooltip,
Legend
)

function BudgetTracker(){

/* TRIP INFO */

const [tripName,setTripName] = useState("")
const [traveller,setTraveller] = useState("")
const [days,setDays] = useState("")

/* BUDGET DATA */

const [budget,setBudget] = useState(0)
const [food,setFood] = useState(0)
const [hotel,setHotel] = useState(0)
const [transport,setTransport] = useState(0)
const [shopping,setShopping] = useState(0)


/* CALCULATIONS */

const totalSpent =
Number(food) +
Number(hotel) +
Number(transport) +
Number(shopping)

const remaining = budget - totalSpent


/* PIE CHART DATA */

const pieData = {
labels:["Food","Hotel","Transport","Shopping"],
datasets:[
{
data:[food,hotel,transport,shopping],
backgroundColor:[
"#ff6384",
"#36a2eb",
"#ffce56",
"#4caf50"
]
}
]
}


/* BAR CHART DATA */

const barData = {
labels:["Food","Hotel","Transport","Shopping"],
datasets:[
{
label:"Expense by Category",
data:[food,hotel,transport,shopping],
backgroundColor:"#36a2eb"
}
]
}


/* LINE CHART DATA */

const lineData = {
labels:["Budget","Spent","Remaining"],
datasets:[
{
label:"Budget Overview",
data:[budget,totalSpent,remaining],
borderColor:"#ff6384",
fill:false
}
]
}



/* EXPORT PDF FUNCTION */

const downloadPDF = async () => {

const pdf = new jsPDF("p","mm","a4")

/* GET FRIENDS */

const storedFriends =
JSON.parse(localStorage.getItem("friends")) || []

const friendNames =
storedFriends.map(friend => friend.name)

const travellers =
traveller
? [traveller,...friendNames]
: friendNames


/* -------- PAGE 1 : TRIP SUMMARY -------- */

pdf.setFontSize(22)
pdf.text("GoTrip Travel Expense Report",40,20)

pdf.setFontSize(14)

pdf.text(`Trip Name: ${tripName}`,20,50)
pdf.text(`Travellers: ${travellers.join(", ")}`,20,60)
pdf.text(`Duration: ${days} Days`,20,70)
pdf.text(`Total Budget: ₹${budget}`,20,80)

pdf.text(`Total Spent: ₹${totalSpent}`,20,90)
pdf.text(`Remaining Budget: ₹${remaining}`,20,100)

pdf.text("Generated by GoTrip",20,120)



/* -------- PAGE 2 : DASHBOARD -------- */

const dashboard =
document.getElementById("budget-dashboard")

const canvas =
await html2canvas(dashboard,{scale:2})

const imgData =
canvas.toDataURL("image/png")

const imgWidth = 190
const imgHeight =
canvas.height * imgWidth / canvas.width

pdf.addPage()

pdf.setFontSize(18)
pdf.text("Expense Dashboard",70,20)

pdf.addImage(imgData,"PNG",10,30,imgWidth,imgHeight)



/* -------- PAGE 3 : EXPENSE BREAKDOWN -------- */

pdf.addPage()

pdf.setFontSize(18)
pdf.text("Expense Breakdown",70,20)

pdf.setFontSize(12)

pdf.text(`Food: ₹${food}`,20,50)
pdf.text(`Hotel: ₹${hotel}`,20,60)
pdf.text(`Transport: ₹${transport}`,20,70)
pdf.text(`Shopping: ₹${shopping}`,20,80)

pdf.text(`Total Spent: ₹${totalSpent}`,20,100)



/* -------- PAGE 4 : TRAVELLERS -------- */

pdf.addPage()

pdf.setFontSize(18)
pdf.text("Trip Travellers",70,20)

pdf.setFontSize(12)

travellers.forEach((name,index)=>{
pdf.text(`${index+1}. ${name}`,20,50 + (index*10))
})


pdf.save("GoTrip-Trip-Report.pdf")

}



return(

<div className="budget-container">

<div className="budget-dashboard" id="budget-dashboard">

<h1>Total Trip Budget Dashboard</h1>


{/* TRIP INFO */}

<div className="trip-info">

<input
type="text"
placeholder="Trip Name (Example: Goa Trip)"
value={tripName}
onChange={(e)=>setTripName(e.target.value)}
/>

<input
type="text"
placeholder="Traveller Name"
value={traveller}
onChange={(e)=>setTraveller(e.target.value)}
/>

<input
type="number"
placeholder="Trip Duration (Days)"
value={days}
onChange={(e)=>setDays(e.target.value)}
/>

</div>


{/* INPUT SECTION */}

<div className="inputs">

<input
type="number"
placeholder="Enter Total Budget"
onChange={(e)=>setBudget(e.target.value)}
/>

<input
type="number"
placeholder="Food Expense"
onChange={(e)=>setFood(e.target.value)}
/>

<input
type="number"
placeholder="Hotel Expense"
onChange={(e)=>setHotel(e.target.value)}
/>

<input
type="number"
placeholder="Transport Expense"
onChange={(e)=>setTransport(e.target.value)}
/>

<input
type="number"
placeholder="Shopping Expense"
onChange={(e)=>setShopping(e.target.value)}
/>

</div>


{/* BUDGET SUMMARY */}

<div className="budget-cards">

<div className="card">
<h3>Total Budget</h3>
<p>₹{budget}</p>
</div>

<div className="card">
<h3>Total Spent</h3>
<p>₹{totalSpent}</p>
</div>

<div className="card">
<h3>Remaining</h3>
<p>₹{remaining}</p>
</div>

<div className="card">
<h3>Daily Limit</h3>
<p>₹{budget ? Math.floor(budget/5) : 0}</p>
</div>

</div>


{/* CHART GRID */}

<div className="charts-grid">

<div className="chart-card">
<h3>Expense Distribution</h3>
<Pie data={pieData}/>
</div>

<div className="chart-card">
<h3>Category Comparison</h3>
<Bar data={barData}/>
</div>

<div className="chart-card large-chart">
<h3>Budget Overview</h3>
<Line data={lineData}/>
</div>

</div>


{/* EXPORT BUTTON */}

<button className="export-btn" onClick={downloadPDF}>
Download Full Trip Report
</button>

</div>

</div>

)

}

export default BudgetTracker

